import os
import tempfile
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

def generate_report(name: str, role: str, skills: list, gap: list, match_score: float) -> str:
    output_path = os.path.join(tempfile.gettempdir(), f"career_report_{name.replace(' ', '_')}.pdf")
    doc = SimpleDocTemplate(output_path, rightMargin=inch, leftMargin=inch,
                            topMargin=inch, bottomMargin=inch)

    styles = getSampleStyleSheet()
    accent = ParagraphStyle("accent", parent=styles["Normal"],
                            textColor=colors.HexColor("#1D9E75"), fontSize=11)
    heading2 = ParagraphStyle("h2", parent=styles["Heading2"],
                               textColor=colors.HexColor("#0e1a2b"))

    content = [
        Paragraph("🚀 AI Career Intelligence Report", styles["Title"]),
        Spacer(1, 6),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1D9E75")),
        Spacer(1, 12),
        Paragraph(f"<b>Name:</b> {name}", styles["Normal"]),
        Paragraph(f"<b>Target Role:</b> {role.title()}", styles["Normal"]),
        Paragraph(f"<b>Match Score:</b> {match_score}%", accent),
        Spacer(1, 12),
        Paragraph("Top Skills for This Role", heading2),
        HRFlowable(width="100%", thickness=0.5, color=colors.grey),
        Spacer(1, 6),
    ]

    for s in skills:
        content.append(Paragraph(f"• {s.title()}", styles["Normal"]))

    content += [
        Spacer(1, 12),
        Paragraph("Skill Gap — Areas to Improve", heading2),
        HRFlowable(width="100%", thickness=0.5, color=colors.grey),
        Spacer(1, 6),
    ]

    if gap:
        for g in gap:
            content.append(Paragraph(f"• {g.title()}", styles["Normal"]))
    else:
        content.append(Paragraph("✅ No skill gaps detected!", accent))

    content += [
        Spacer(1, 20),
        Paragraph("Generated by AI Job Market Intelligence", styles["Italic"]),
    ]

    doc.build(content)
    return output_path